services:
  test:
    image: asomaaroufiniyaa/test
    container_name: test
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL="mongodb://mongo:27017"

    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/data/db
  
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /home/officer/projects/Automated_DB_Backups/app/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - test

